apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-pods-edit
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployments-pods-edit-binding
subjects:
- kind: User
  name: deploy_edit
roleRef:
  kind: ClusterRole
  name: deployments-pods-edit
  apiGroup: rbac.authorization.k8s.io
