apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployments-pods-view
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployments-pods-view-binding
subjects:
- kind: User
  name: deploy_view
roleRef:
  kind: ClusterRole
  name: deployments-pods-view
  apiGroup: rbac.authorization.k8s.io
