apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: prod
 name: prod_admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_admin-binding
  namespace: prod
subjects:
- kind: User
  name: prod_admin
roleRef:
  kind: Role
  name: prod_admin-role
  apiGroup: rbac.authorization.k8s.io
