apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: prod
 name: prod_view-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod_view-binding
  namespace: prod
subjects:
- kind: User
  name: prod_view
roleRef:
  kind: Role
  name: prod_view-role
  apiGroup: rbac.authorization.k8s.io
