apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 namespace: default
 name: sa-namespace-admin-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-namespace-admin-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-namespace-admin
roleRef:
  kind: Role
  name: sa-namespace-admin-role
  apiGroup: rbac.authorization.k8s.io
